version: '3.7'

services:
  pgvector:
    image: ankane/pgvector:v0.5.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    command:
      - "postgres"
      - "-c"
      - "max_connections=150"
      - "-c"
      - "work_mem=32MB"
      - "-c"
      - "shared_buffers=4GB"
    deploy:
      resources:
        limits:
          memory: 25Gb
